# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: https://gist.github.com/dbaynard/9693107a883a6282f52f22785d0072e2/raw/20c61f5042ca1b3fe3e6e93581533af6dc70b7bb

# Local packages, usually specified by relative directory name
packages:
- 'ucam-webauth-types'
- 'ucam-webauth'
- 'servant-raven'
- 'servant-raven-server'
- 'servant-redirect'
- 'servant-redirect-server'
- 'raven-wai'
- 'rio-servant'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#

# GHC options

# Allow newer packages than cabal bounds suggest?
allow-newer: true

pvp-bounds: both
