flags: {}
extra-dep: true
resolver: ghc-7.10
packages:
- '.'
extra-deps:
- ReadArgs-1.2.2
- basic-prelude-0.5.0
- classy-prelude-0.12.1.1
- errors-2.0.0
- monoid-subclasses-0.4.1.2
- mutable-containers-0.3.0
- primes-0.2.1.0
- timerep-2.0.0.1
- warp-3.0.13.1
