flags: {}
extra-dep: true
resolver: ghc-7.10
packages:
- '.'
extra-deps:
- RSA-2.1.0.1
- ReadArgs-1.2.2
- basic-prelude-0.5.0
- bytestring-builder-0.10.6.0.0
- classy-prelude-0.12.1.1
- classy-prelude-conduit-0.12.0.1
- classy-prelude-yesod-0.12.0.1
- errors-2.0.0
- fast-logger-2.3.1
- hjsmin-0.1.4.8
- html-conduit-1.2.0
- language-javascript-0.5.13.4
- monad-logger-0.3.13.2
- monoid-subclasses-0.4.1.2
- mutable-containers-0.3.0
- nonce-1.0.2
- persistent-2.2
- persistent-template-2.1.3.4
- primes-0.2.1.0
- timerep-2.0.0.1
- wai-app-static-3.0.1.1
- wai-extra-3.0.10
- wai-logger-2.2.4.1
- warp-3.0.13.1
- yesod-1.4.1.5
- yesod-auth-1.4.6
- yesod-core-1.4.12
- yesod-form-1.4.4.1
- yesod-newsfeed-1.4.0.1
- yesod-persistent-1.4.0.3
- yesod-static-1.4.0.4
- yesod-test-1.4.3.1
