name: ucam-webauth
version: '0.1.0.0'
synopsis: The Ucam-Webauth protocol, used by Raven
description: |
  An implementation of the Ucam-Webauth protocol, as used by the University of Cambridge’s
  Raven authentication service.
category: Web
author: David Baynard <ucamwebauth@baynard.me>
maintainer: David Baynard <ucamwebauth@baynard.me>
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

extra-source-files:
- Changelog.md
- README.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances

flags:
  dev:
    description: Compile for development
    default: false
    manual: true

when:
- condition: flag(dev)
  ghc-options: -ddump-minimal-imports

dependencies:
  - aeson >=1.2
  - attoparsec >=0.13.2.2
  - base >=4.11.0.0 && <4.13
  - bytestring >=0.10.8.2
  - containers >=0.5.11.0 && <0.7
  - cryptonite >=0.25
  - errors >=2.3.0
  - http-api-data >=0.3.8.1 && <0.5
  - http-types >=0.12.2
  - microlens >=0.4.9.1
  - microlens-mtl >=0.1.11.1
  - mtl >=2.2.2
  - parser-combinators >=1.0.0
  - pem >=0.2.4
  - text >=0.11 && <1.2.3.0 || >=1.2.3.1
  - time >=1.8.0.2
  - ucam-webauth-types >=0.1.0.0
  - x509 >=1.7.5

library:
  source-dirs: src
  exposed-modules:
  - UcamWebauth
  - UcamWebauth.Internal
  - UcamWebauth.Parser
  - UcamWebauth.WLS
  other-modules: []

tests:
  test:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options: -Wall
    generated-other-modules:
    - Paths_ucam_webauth
    dependencies:
    - QuickCheck >=2.11.3
    - generic-random >=1.2.0.0
    - here >=1.2.13
    - hspec >=2.0.0 && <2.7
    - quickcheck-instances >=0.3.19
    - time-qq >=0.0.1.0
    - ucam-webauth-types
    build-tools:
    - hspec-discover
