name: ucam-webauth
version: '0.1.0'
synopsis: The Ucam-Webauth protocol, used by Raven
description: Please see README.md
category: Web
author: David Baynard
maintainer: ucamwebauth@baynard.me
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -ddump-minimal-imports

dependencies:
- aeson >=1.2
- attoparsec
- base >=4 && <5
- base64-bytestring
- bytestring >=0.9 && <0.11
- http-types
- time
- ucam-webauth-types
- microlens
- containers
- cryptonite
- errors
- http-api-data
- microlens-mtl
- mtl
- pem
- text >=0.11 && <2.0
- x509

library:
  source-dirs: src
  exposed-modules:
  - UcamWebauth
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

tests:
  test:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options: -Wall
    dependencies:
    - QuickCheck
    - base
    - generic-arbitrary
    - here
    - hspec >=2.0.0
    - http-api-data
    - quickcheck-instances
    - text
    - time-qq
    - ucam-webauth-types

flags:
  dev:
    description: Build for development
    manual: false
    default: true
