name: Ucam-Webauth
version: '0.0.1'
license: Apache
dependencies:
- base >=4 && <5
- classy-prelude >=0.10.2
library:
  source-dirs: src
  exposed-modules:
  - Network.Protocol.UcamWebauth
  - Network.Wai.Protocol.UcamWebauth
  - Network.Wai.Protocol.Raven.Auth
  - Network.Wai.Protocol.Raven.Test
  - Network.Wai.Protocol.Raven.Example
  dependencies:
  - aeson >=1.2
  - attoparsec
  - base64-bytestring
  - blaze-builder
  - bytestring >=0.9 && <0.11
  - containers
  - cryptonite
  - errors
  - http-types
  - mtl
  - pem
  - text >=0.11 && <2.0
  - time
  - timerep
  - unordered-containers
  - wai
  - warp >=3.1
  - x509
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - Ucam-Webauth
    - hspec >=2.0.0
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
