name: ucam-webauth
version: '0.0.1'
synopsis: The Ucam-Webauth protocol, used by raven
description: Please see README.md
category: Web
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2017 David Baynard
license: Apache
dependencies:
- base >=4 && <5
- ucam-webauth-types
library:
  source-dirs: src
  exposed-modules:
  - Network.Protocol.UcamWebauth
  dependencies:
  - aeson >=1.2
  - attoparsec
  - base64-bytestring
  - bytestring >=0.9 && <0.11
  - containers
  - cryptonite
  - errors
  - http-api-data
  - http-types
  - microlens
  - microlens-mtl
  - mtl
  - pem
  - text >=0.11 && <2.0
  - time
  - timerep
  - x509
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - ucam-webauth
    - hspec >=2.0.0
flags:
  dev:
    description: Build for development
    manual: false
    default: false
