name: ucam-webauth-types
version: '0.1.0.0'
synopsis: Types for the Ucam-Webauth protocol, as used by Raven
description: |
  Types for the implementation of the Ucam-Webauth protocol, as used by the
  University of Cambridge’s Raven authentication service.
category: Web
author: David Baynard <ucamwebauth@baynard.me>
maintainer: David Baynard <ucamwebauth@baynard.me>
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

extra-source-files:
- Changelog.md
- README.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances

flags:
  dev:
    description: Compile for development
    default: false
    manual: true

when:
- condition: flag(dev)
  ghc-options: -ddump-minimal-imports

dependencies:
- base >=4.11.0.0 && <4.13

library:
  source-dirs: src
  exposed-modules:
  - Data.ByteString.B64
  - UcamWebauth.Data
  - UcamWebauth.Data.Internal
  other-modules: []
  dependencies:
  - aeson >=1.2 && <1.5
  - base64-bytestring >=1.0.0.1 && <1.1
  - bytestring >=0.10.8.2 && <0.11
  - case-insensitive >=1.2.0.11 && <1.3
  - containers >=0.5.11.0 && <0.7
  - deepseq >=1.4.3.0 && <1.5
  - http-types >=0.12.2 && <0.13
  - microlens >=0.4.9.1 && <0.5
  - microlens-mtl >=0.1.11.1 && <0.2
  - mtl >=2.2.2 && <2.3
  - text >=0.11 && <1.2.3.0 || >=1.2.3.1 && <1.3
  - time >=1.8.0.2 && <1.10
  - timerep >=2.0.0.2 && <2.1

tests:
  test:
    main: Spec.hs
    source-dirs: test
    generated-other-modules:
    - Paths_ucam_webauth_types
    dependencies:
    - hspec >=2.0.0 && <2.7
    build-tools:
    - hspec-discover
