name: ucam-webauth-types
version: '0.1.0'
synopsis: Types for the Ucam-Webauth protocol, as used by Raven
description: Please see README.md
category: Web
author: David Baynard
maintainer: ucamwebauth@baynard.me
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -ddump-minimal-imports

dependencies:
- aeson >=1.2
- base >=4.10.0.0 && <5
- base64-bytestring
- bytestring >=0.9 && <0.11
- case-insensitive
- containers
- errors
- http-types
- microlens
- microlens-mtl
- mtl
- text >=0.11 && <2.0
- time
- timerep
- deepseq

library:
  source-dirs: src
  exposed-modules:
  - Data.ByteString.B64
  - UcamWebauth.Data
  - UcamWebauth.Data.Internal
  dependencies: []
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - ucam-webauth-types
    - hspec >=2.0.0

flags:
  dev:
    description: Build for development
    manual: false
    default: true
