name: ucam-webauth-types
version: '0.1.0.0'
synopsis: Types for the Ucam-Webauth protocol, as used by Raven
description: |
  Types for the implementation of the Ucam-Webauth protocol, as used by the
  University of Cambridge’s Raven authentication service.
category: Web
author: David Baynard <ucamwebauth@baynard.me>
maintainer: David Baynard <ucamwebauth@baynard.me>
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

extra-source-files:
- Changelog.md
- README.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances

flags:
  dev:
    description: Compile for development
    default: false
    manual: true

when:
- condition: flag(dev)
  ghc-options: -ddump-minimal-imports

dependencies:
- base >=4.11.0.0

library:
  source-dirs: src
  exposed-modules:
  - Data.ByteString.B64
  - UcamWebauth.Data
  - UcamWebauth.Data.Internal
  other-modules: []
  dependencies:
  - aeson >=1.2
  - base64-bytestring
  - bytestring
  - case-insensitive
  - containers
  - http-types
  - microlens
  - microlens-mtl
  - mtl
  - text >=0.11 && < 1.2.3.0 || >= 1.2.3.1
  - time
  - timerep
  - deepseq

tests:
  test:
    main: Spec.hs
    source-dirs: test
    generated-other-modules:
    - Paths_ucam_webauth_types
    dependencies:
    - hspec >=2.0.0
    build-tools:
    - hspec-discover
