name: ucam-webauth-types
version: '0.1.0'
synopsis: Types for the Ucam-Webauth protocol, as used by Raven
description: Please see README.md
category: Web
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2017 David Baynard
license: Apache
git: github.com/dbaynard/UcamWebauth

dependencies:
- aeson >=1.2
- base >=4 && <5
- base64-bytestring
- bytestring >=0.9 && <0.11
- containers
- errors
- http-types
- microlens
- microlens-mtl
- mtl
- text >=0.11 && <2.0
- time
- timerep
library:
  source-dirs: src
  exposed-modules:
  - Network.Protocol.UcamWebauth.Data
  - Network.Protocol.UcamWebauth.Data.Internal
  dependencies: []
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - ucam-webauth
    - hspec >=2.0.0
flags:
  dev:
    description: Build for development
    manual: false
    default: false
