name:                servant-raven
version:             0.0.1.0
synopsis:            Combinators for raven
description:         See README.md
license:             APACHE
author:              David Baynard
maintainer:          davidbaynard@gmail.com
copyright:           2017 David Baynard
category:            Web

dependencies:
- base >= 4.7 && < 5
- bytestring
- errors
- jose
- microlens-mtl
- mtl
- servant-auth
- servant-auth-server
- text
- time

library:
  source-dirs: src
  exposed-modules: []
  dependencies:
  - aeson
  - errors
  - containers
  - servant-server
  - Ucam-Webauth
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  servant-raven-example:
    source-dirs:      app
    main:             Main.lhs
    dependencies:
    - microlens
    - optparse-generic
    - wai-extra
    - warp
    - yaml

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - servant-raven
    - hspec >=2.0.0
flags:
  dev:
    description: Build for development
    manual: false
    default: false
