name:                servant-raven
version:             0.0.1.0
synopsis:            Combinators for raven
description:         See README.md
license:             APACHE
author:              David Baynard
maintainer:          davidbaynard@gmail.com
copyright:           2017 David Baynard
category:            Web

dependencies:
- base >= 4.7 && < 5
- errors
- jose
- microlens-mtl
- reflection
- servant-auth-server
- servant-server
- text
- time

library:
  source-dirs: src
  exposed-modules: []
  dependencies:
  - aeson
  - network-uri
  - servant
  - template-haskell
  - Ucam-Webauth
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  servant-raven-example:
    source-dirs:      app
    main:             Main.lhs
    dependencies:
    - bytestring
    - microlens
    - mtl
    - optparse-generic
    - servant-auth
    - servant-raven
    - wai-extra
    - warp
    - yaml

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - servant-raven
    - hspec >=2.0.0
flags:
  dev:
    description: Build for development
    manual: false
    default: false
