name: servant-raven
version: '0.1.0'
synopsis: Servant API for Raven authentication
description: See README.md
license: Apache
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2017 David Baynard
category: Web
git: github.com/dbaynard/UcamWebauth

dependencies:
- base >= 4.7 && < 5
- servant
- ucam-webauth-types

library:
  source-dirs: src
  exposed-modules:
  - Servant.UcamWebauth.API
  - Servant.UcamWebauth.Settings
  - URI.Convert
  dependencies:
  - bytestring
  - errors
  - microlens
  - microlens-mtl
  - network-uri
  - reflection
  - text
  - uri-bytestring
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - servant-raven
    - hspec >=2.0.0
flags:
  dev:
    description: Build for development
    manual: false
    default: false
