name: servant-raven-server
version: '0.1.0'
synopsis: Servant server for Raven authentication
description: See README.md
license: BSD-3-Clause OR Apache-2.0
author: David Baynard
maintainer: ucamwebauth@baynard.me
copyright: 2018 David Baynard
category: Web
github: dbaynard/UcamWebauth

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -pgmL markdown-unlit

flags:
  dev:
    description: Compile for development
    default: false
    manual: true

when:
- condition: flag(dev)
  ghc-options: -ddump-minimal-imports

dependencies:
- base >= 4.7 && < 5
- servant-raven
- servant-server

extra-source-files:
- static/*.crt

library:
  source-dirs: src
  exposed-modules:
  - Extra.Servant.Auth
  - Extra.Servant.Redirect
  - Servant.UcamWebauth
  dependencies:
  - aeson
  - errors
  - jose
  - microlens
  - microlens-mtl
  - mtl
  - servant
  - servant-auth-server
  - time
  - ucam-webauth
  - ucam-webauth-types
  - unliftio

executables:
  servant-raven-example:
    source-dirs:      app
    main:             Main.lhs
    build-tools:
    - markdown-unlit
    dependencies:
    - bytestring
    - errors
    - jose
    - microlens
    - microlens-mtl
    - mtl
    - optparse-generic
    - reflection
    - servant-auth
    - servant-auth-server
    - servant-raven-server
    - text
    - time
    - ucam-webauth
    - unliftio
    - unliftio-core
    - uri-bytestring
    - wai-extra
    - warp
    - yaml

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - bytestring
    - hspec >=2.0.0
    - servant-raven-server
    - text
    - uri-bytestring
    build-tools:
    - hspec-discover
