name: servant-raven-server
version: '0.1.0'
synopsis: Servant server for Raven authentication
description: See README.md
license: BSD-3-Clause OR Apache-2.0
author: David Baynard
maintainer: ucamwebauth@baynard.me
copyright: 2018 David Baynard
category: Web
github: dbaynard/UcamWebauth

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -ddump-minimal-imports
- -pgmL markdown-unlit

dependencies:
- base >= 4.7 && < 5
- bytestring
- errors
- jose
- microlens-mtl
- mtl
- network-uri
- reflection
- servant-auth-server
- servant-raven
- servant-server
- text
- time
- ucam-webauth
- unliftio
- uri-bytestring

extra-source-files:
- static/*.crt

library:
  source-dirs: src
  exposed-modules:
  - Extra.Servant.Auth
  - Extra.Servant.Redirect
  - Servant.UcamWebauth
  dependencies:
  - aeson
  - microlens
  - servant
  - ucam-webauth-types
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  servant-raven-example:
    source-dirs:      app
    main:             Main.lhs
    build-tools:
    - markdown-unlit
    dependencies:
    - bytestring
    - microlens
    - optparse-generic
    - servant-auth
    - servant-raven-server
    - wai-extra
    - warp
    - yaml

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - servant-raven-server
    - hspec >=2.0.0
    - generic-arbitrary
    - QuickCheck
    - quickcheck-instances

flags:
  dev:
    description: Build for development
    manual: false
    default: true
