name: raven-wai
version: '0.1.0.0'
synopsis: Raven authentication as Wai middleware
description: |
  The UcamWebauth protocol instantiated to the University of Cambridge’s Raven service, as Wai middleware.
category: Web
author: David Baynard <ucamwebauth@baynard.dev>
maintainer: David Baynard <ucamwebauth@baynard.dev>
copyright: 2018 David Baynard
license: BSD-3-Clause OR Apache-2.0
github: dbaynard/UcamWebauth

extra-source-files:
- Changelog.md
- README.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances

flags:
  dev:
    description: Compile for development
    default: false
    manual: true

when:
- condition: flag(dev)
  ghc-options: -ddump-minimal-imports

dependencies:
- base >=4 && <5

library:
  source-dirs: src
  exposed-modules:
  - Network.Wai.Protocol.Raven.Auth
  - Network.Wai.Protocol.Raven.Internal
  - Network.Wai.Protocol.Raven.Test
  - Network.Wai.Protocol.UcamWebauth
  other-modules: []
  dependencies:
  - containers
  - ucam-webauth-types
  - bytestring >=0.9 && <0.11
  - microlens-mtl
  - wai

executables:
  raven-wai-example:
    source-dirs: app
    main: Main.lhs
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    build-tools:
    - markdown-unlit
    dependencies:
    - aeson
    - bytestring
    - errors
    - http-types
    - microlens
    - microlens-mtl
    - mtl
    - raven-wai
    - text >=0.11 && <2.0
    - time
    - ucam-webauth
    - wai
    - warp >=3.2.0

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    generated-other-modules:
    - Paths_raven_wai
    dependencies:
    - hspec >=2.0.0
    build-tools:
    - hspec-discover
