name: raven-wai
version: '0.0.1'
license: Apache
dependencies:
- base >=4 && <5
- Ucam-Webauth
library:
  source-dirs: src
  exposed-modules:
  - Network.Wai.Protocol.UcamWebauth
  - Network.Wai.Protocol.Raven.Auth
  - Network.Wai.Protocol.Raven.Test
  - Network.Wai.Protocol.Raven.Example
  dependencies:
  - bytestring >=0.9 && <0.11
  - containers
  - errors
  - http-types
  - microlens
  - microlens-mtl
  - mtl
  - text >=0.11 && <2.0
  - time
  - wai
  - warp >=3.2.0
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - raven-wai
    - hspec >=2.0.0
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
